"""Router entrypoint for the UserPromptSubmit hook.

Reads JSON on stdin (Claude CLI hook payload), classifies the prompt,
picks skills/agents, and emits a routing block on stdout that Claude
sees as additional context.

Exit codes: 0 = success, pass-through stdout; 1 = soft failure, no injection.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any

from . import classifier, config, registry

LOG_PATH = Path.home() / ".claude" / "ccpilot" / "log.jsonl"


def _read_input() -> dict[str, Any]:
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return {}
        return json.loads(raw)
    except (json.JSONDecodeError, OSError):
        return {}


def _log(entry: dict[str, Any]) -> None:
    try:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with LOG_PATH.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
    except OSError:
        pass


def _swarm_plan(intent: str, complexity: float, max_agents: int) -> dict[str, Any]:
    """Decide number + roles of subagents based on intent and complexity."""
    heavy_intents = {"multi_file_research", "security", "planning", "devops"}
    if complexity < 0.35 and intent not in heavy_intents:
        return {"agents": 0, "roles": []}
    roles_by_intent = {
        "multi_file_research": ["orchestrator", "explorer", "explorer", "explorer", "reviewer"],
        "security": ["security-auditor", "explorer", "explorer", "reviewer"],
        "design_ui": ["ui-designer", "explorer", "reviewer"],
        "devops": ["explorer", "implementer", "reviewer"],
        "planning": ["orchestrator", "explorer", "explorer", "reviewer"],
        "scoped_edit": ["implementer", "reviewer"],
        "external_web": ["explorer"],
    }
    roles = roles_by_intent.get(intent, ["explorer"])
    # Heavy intents get a floor of 3 agents; scoped work scales with complexity.
    if intent in heavy_intents:
        n = min(max_agents, max(3, int(round(len(roles) * (0.4 + complexity)))))
    else:
        n = min(max_agents, max(1, int(round(len(roles) * (0.5 + complexity)))))
    return {"agents": n, "roles": roles[:n]}


def _render_block(
    c: classifier.Classification,
    skills: list[registry.Skill],
    swarm: dict[str, Any],
) -> str:
    lines = ["<ccpilot-routing>"]
    lines.append(f"intent: {c.intent}")
    lines.append(f"complexity: {c.complexity:.2f} (confidence {c.confidence:.2f})")
    if skills:
        lines.append("suggested_skills: " + ", ".join(s.name for s in skills))
    if swarm["agents"] > 0:
        lines.append(
            f"suggested_subagents: {swarm['agents']}x parallel ["
            + ", ".join(swarm["roles"]) + "]"
        )
    lines.append(
        "note: This block was auto-generated by ccpilot. "
        "Invoke suggested skills via the Skill tool and spawn subagents via the Agent tool as needed."
    )
    lines.append("</ccpilot-routing>")
    return "\n".join(lines)


def _disabled_via_env() -> bool:
    val = os.environ.get("CCPILOT_DISABLED", "").strip().lower()
    return val in ("1", "true", "yes", "on")


def main() -> int:
    # Env var short-circuit for cost management — no config edit required.
    # Set CCPILOT_DISABLED=1 to bypass routing (and any LLM escalation) entirely.
    if _disabled_via_env():
        return 0
    cfg = config.load()
    if not cfg["router"].get("enabled", True):
        return 0

    payload = _read_input()
    prompt = payload.get("prompt") or payload.get("user_prompt") or ""
    if not isinstance(prompt, str):
        return 0

    c = classifier.classify(prompt)
    c = classifier.maybe_escalate(prompt, c, cfg)
    if cfg.get("learning", {}).get("enabled", False):
        from . import memory
        try:
            c.confidence = max(0.0, min(1.0, c.confidence + memory.nudge(c.intent)))
        except Exception:
            pass

    reg = registry.load_or_build()
    semantic_on = cfg.get("search", {}).get("enabled", True)

    # Trivial → quick_answer promotion: short lookup/explain prompts ("what
    # does X do", "explain this stack trace") currently die at the trivial
    # gate. If semantic search finds a clearly-relevant skill, reclassify
    # as quick_answer so the routing block is emitted for a single skill
    # suggestion (no swarm, no heavy context).
    promoted_skills: list[registry.Skill] = []
    if c.intent == "trivial" and semantic_on:
        promoted_skills = registry.semantic_top(reg, prompt.lower())
        if promoted_skills:
            c.intent = "quick_answer"
            c.confidence = max(c.confidence, 0.6)

    skills = registry.pick_skills(
        reg, c.intent, prompt.lower(), semantic=semantic_on,
    )
    if promoted_skills and not skills:
        skills = promoted_skills[:2]
    swarm = _swarm_plan(c.intent, c.complexity, cfg["swarm"].get("max_agents", 5))

    if cfg.get("guidance", {}).get("enabled", True):
        from . import guidance
        rules = guidance.load(Path.cwd())
        skill_names = [s.name for s in skills]
        new_names, new_agents = guidance.apply(
            rules, c.intent, c.complexity, skill_names, swarm["agents"]
        )
        skills = [s for s in skills if s.name in set(new_names)]
        # Preserve any required-skill additions from guidance.apply
        existing = {s.name for s in skills}
        for n in new_names:
            if n not in existing:
                skills.append(registry.Skill(name=n, path="", description="(required by CLAUDE.md)"))
        swarm["agents"] = new_agents
        if new_agents == 0:
            swarm["roles"] = []

    should_emit = c.intent != "trivial" and (skills or swarm["agents"] > 0)
    block = _render_block(c, skills, swarm) if should_emit else ""

    if cfg.get("learning", {}).get("enabled", False):
        try:
            sidecar = LOG_PATH.parent / "last_intent.txt"
            sidecar.parent.mkdir(parents=True, exist_ok=True)
            sidecar.write_text(c.intent)
        except OSError:
            pass

    _log({
        "ts": time.time(),
        "pid": os.getpid(),
        "classification": c.to_dict(),
        "skills": [s.name for s in skills],
        "swarm": swarm,
        "emitted": bool(block),
    })

    if block and cfg["router"].get("visible_routing_block", True):
        # stdout -> injected into model context (system-reminder)
        sys.stdout.write(block + "\n")
        # stderr -> shown visibly in the terminal transcript
        sys.stderr.write(block + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
